import FaqSection from "@/components/pages/faq/FaqSection";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Faq = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Faq" />
      <FaqSection />
    </MainBody>
  );
};

export default Faq;
