import EventSection from "@/components/pages/event/EventSection";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const createEvent = () => {
  return (
    <MainBody>
      <EventSection />
    </MainBody>
  );
};

export default createEvent;
