import CommonDetails from "@/components/pages/albumb-details/CommonDetails";
import ConveterHead from "@/components/pages/albumb-details/ConveterHead";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const workoutAll = () => {
  return (
    <MainBody>
      <CommonDetails image="/img/details/allwork-single.jpg">
        <ConveterHead name="ASD" songTitle="44m" />
      </CommonDetails>
    </MainBody>
  );
};

export default workoutAll;
