import PopularAlbums from "@/components/pages/albums/PopularAlbums";
import Trending from "@/components/pages/albums/Trending";
import BreadCrumb from "@/components/shared/BreadCrum";
import Footer from "@/components/shared/Footer";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const albums = () => {
  return (
    <MainBody>
      <BreadCrumb page="Albums" />
      <Trending />
      <PopularAlbums />
      <Footer />
    </MainBody>
  );
};

export default albums;
