import SongUpdateSection from "@/components/pages/genres-allsong/SongUpdateSection";
import WorkoutSlider from "@/components/pages/workout-allsong/WorkoutSlider";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const workoutAll = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Workout" />
      <WorkoutSlider />
      <SongUpdateSection />
    </MainBody>
  );
};

export default workoutAll;
