import PopularArtists from "@/components/pages/artists/PopularArtists";
import FeaturedShows from "@/components/pages/home/FeaturedShows";
import BreadCrumb from "@/components/shared/BreadCrum";
import Footer from "@/components/shared/Footer";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const artists = () => {
  return (
    <MainBody>
      <BreadCrumb page="Popular Artists" />
      <PopularArtists />
      <FeaturedShows />
      <Footer />
    </MainBody>
  );
};

export default artists;
