import { songUpgradeData } from "@/../public/data/songUpgrdeData";
import SongUpgrade from "@/components/pages/albumb-allsong/SongUpgrade";
import TopSinger from "@/components/pages/albumb-allsong/TopSinger";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const albumAllSong = () => {
  return (
    <MainBody>
      <TopSinger />
      <SongUpgrade sectionTitle="Mix All Songs" artistSong={songUpgradeData} />
    </MainBody>
  );
};

export default albumAllSong;
