import Checkout from "@/components/pages/checkout/Checkout";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const checkoutSection = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Check Out" />
      <Checkout />
    </MainBody>
  );
};

export default checkoutSection;
