import Workout from "@/components/pages/home/Workout";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const workout = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Workout" />
      <Workout />
    </MainBody>
  );
};

export default workout;
