import LatestPost from "@/components/pages/blog/LatestPost";
import BreadCrumb from "@/components/shared/BreadCrum";
import Footer from "@/components/shared/Footer";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const blog = () => {
  return (
    <MainBody>
      <BreadCrumb page="Post" />
      <LatestPost />
      <Footer />
    </MainBody>
  );
};

export default blog;
