import GenresSlider from "@/components/pages/genres-allsong/GenresSlider";
import SongUpdateSection from "@/components/pages/genres-allsong/SongUpdateSection";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const genresAllsong = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Genres" />
      <GenresSlider />
      <SongUpdateSection />
    </MainBody>
  );
};

export default genresAllsong;
