import CommonDetails from "@/components/pages/albumb-details/CommonDetails";
import Footer from "@/components/shared/Footer";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const albumDetails = () => {
  return (
    <MainBody>
      <CommonDetails />
      <Footer />
    </MainBody>
  );
};

export default albumDetails;
