import Navbar from "@/components/shared/Navbar";
import { poppins } from "@/utils/fonts";
import "material-symbols";
import { Metadata } from "next";
import ".././styles/sass/main.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
