import AudioPlayerModal from "@/components/pages/explore/AudioPlayerModal";
import AddToPlaylistModal from "@/components/shared/AddToPlaylistModal";
import DeletePostModal from "@/components/shared/DeletePostModal";
import ReportModal from "@/components/shared/ReportModal";
import SharedModal from "@/components/shared/SharedModal";
import { poppins } from "@/utils/fonts";
import "material-symbols";
import { Metadata } from "next";
import { Suspense } from "react";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import "swiper/scss/scrollbar";
import ".././styles/sass/main.scss";
import "../styles/all.min.css";
import Loader from "./Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          <Suspense fallback={<Loader />}>{children}</Suspense>
        </main>
        <AddToPlaylistModal />
        <SharedModal />
        <DeletePostModal />
        <ReportModal />
        <AudioPlayerModal />
      </body>
    </html>
  );
}
