import ProductDetails from "@/components/pages/cart/ProductDetails";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cart = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Cart" />
      <ProductDetails />
    </MainBody>
  );
};

export default cart;
