import FeatureShowSection from "@/components/pages/freature-show/FeatureShowSection";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const FeatureShow = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Show" />
      <FeatureShowSection />
    </MainBody>
  );
};

export default FeatureShow;
