import GenresSection from "@/components/pages/genres/GenresSection";
import BreadCrumSingle from "@/components/shared/BreadCrumSingle";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const genres = () => {
  return (
    <MainBody>
      <BreadCrumSingle page="Genres" />
      <GenresSection />
    </MainBody>
  );
};

export default genres;
