import TrendingSection from "@/components/pages/trending/TrendingSection";
import BreadCrumb from "@/components/shared/BreadCrum";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const albumDetails = () => {
  return (
    <MainBody>
      <BreadCrumb page="Trending" />
      <TrendingSection />
    </MainBody>
  );
};

export default albumDetails;
