import BlogDetailsPost from "@/components/pages/blog-details/BlogDetailsPost";
import MainBody from "@/components/shared/MainBody";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const blogDetails = () => {
  return (
    <MainBody>
      <BlogDetailsPost />
    </MainBody>
  );
};

export default blogDetails;
